### ISSUE TITLE
Possible to add points after initialization

### ISSUE THREAD

**Issue by turban** [darkskyapp/sphere-knn#1]
I would like to add additional latitude/longitude points after initialisation. Now, I need to create a new index when I want to add more points to the array.

**Comment by ghost** [comment]
KD-trees can't, in general, be built incrementally. So, adding this feature would mean rewriting the library from scratch.

That's not necessarily a bad thing, though. Give me some time to ponder potential solutions and I'll see what I can do.

**Comment by turban** [comment]
ok, thanks!

**Comment by ghost** [comment]
My original plan was to use a bounding volume hierarchy (BVH), but that won't work—it can very easily become far too unbalanced to be practical.

Another option that doesn't work too well is a hierarchical grid—it works beautifully if your points are distributed uniformly across the globe, but if you have 10,000 points in downtown Manhattan, the whole thing falls apart.

So, I'm going to have to survey the literature on how to do this effectively—maybe some kind of probabilistic or self-balancing data structure. I'll keep noodling on it!

**Comment by turban** [comment]
Good luck noodling! It's great to have these possibilities available in JavaScript. sphere-knn and crossfilter is a good match to search and filter geospatial data.

**Comment by ghost** [comment]
Here's a dumb question: how many points are you looking to search and filter? If it's not too many, the stupid solution of just keeping a list and searching through it linearly would work wonders :p

**Comment by turban** [comment]
It could be several thousands points, and I would like the the search to be instant so a tree structure is great. Updates are not happening that often, so recreating the tree structure on each data update is acceptible, it would just be a nice optimisation if possible. Crossfilter allows me to add data with the add method: https://github.com/square/crossfilter/wiki/API-Reference#crossfilter_add

**Comment by ghost** [comment]
Well, be careful not to optimize prematurely: several thousand points is nothing these days, and the search would still almost certainly be instant. (It'll probably get slow if you start using tens of hundreds of thousands, though.)

I'll try hacking up a simple thing and run some tests on it on my end.
