### ISSUE TITLE
[FAQ] sphere-knn output behaviour

### ISSUE THREAD

**Issue by kirantpatil** [darkskyapp/sphere-knn#3]
Hi,

Please help me to understand the output behaviour.

I opened issue at https://github.com/mapbox/leaflet-knn/issues/9.

Thanks.

**Comment by ghost** [comment]
sphere-knn simply returns a list of objects. The objects are whatever you passed to sphere-knn in the first place!

This is documented in the README: https://github.com/darkskyapp/sphere-knn/blob/master/README.md
