### ISSUE TITLE
ES6 Transpilation

### ISSUE THREAD

**Issue by StephanGeorg** [darkskyapp/sphere-knn#4]
Hey guys. We just realized, that your last release is written in es6. So far, so good, but publishing it to npm causes many errors. See [Using ES6 with npm today](http://mammal.io/articles/using-es6-today/). The whole world is not yet ready for es6 :). In our case it brokes our MeteorJS build.

**Comment by ghost** [comment]
Hi! Thanks for the feedback.

We have no plans to transpile ES6 to older versions of JS... the build structure involved is a way larger can of worms than we're willing to open up. On the other hand, it is a little embarrassing to notice that our `package.json` doesn't have a minimum Node version set... we'll set this and push 1.3.1 to fix it. This way, at least you'll be locked to 1.2.x unless you're running a version of Node that supports it!

**Comment by ghost** [comment]
1.3.1 is now live. Again, sorry about that—it's surprising to us to be behind Node's LTS releases!
