### ISSUE TITLE
Node engines is only a warning

### ISSUE THREAD

**Issue by danielrob** [darkskyapp/sphere-knn#5]
```{ message: 'SyntaxError: Unexpected token: name (Position)',```
We got the above. 

```
"engines": {
  "node": ">=6.0.0"
},
```
Only produces a warning: 
```
npm WARN engine sphere-knn@1.3.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.15","npm":"2.15.1"})
```
Which means [c4fc](https://github.com/darkskyapp/sphere-knn/commit/c4fc0145565c978e095bb92607eb6edb1874c252) is still breaking changes for those on older versions of node.  

It's a bit strange in this case with semver, but I think you should probably release a 1.3.2 as a rollback to support `^1.2.*` npm installs, and then release this as a 2.0.0.

It was certainly breaking changes for us and took a little time to track down.

**Comment by ghost** [comment]
...wow, what a concept.

Thanks for letting us know, I'll try to patch this us as soon as I can. (🦃🍴 will hold it up by a few days, sorry :( )

**Comment by danielrob** [comment]
I should have noted the workaround for those facing this issue is simply to remove the `^` in their package.json declaration (or replace it with a `~`). This has been our approach, so any patch up is mainly to protect anyone else caught unaware.
